### ISSUE TITLE
建议使用互联网历史博物馆等在线服务保留相关页面历史快照

### ISSUE THREAD

**Issue by cpdyj** [evil-huawei/evil-huawei#10]
以防有关方面删帖、篡改

**Comment by CodeDaraW** [comment]
嗯，我也想到这个了，不过目前找不到资料的主要是 251，251 时间太近，Web Archive 都没收录进去，Google Content Cache 无法访问，也没有多少有效的信息。

**Comment by CodeDaraW** [comment]
把 251 的 Google Cache 补上去了。

**Comment by Moeologist** [comment]
关注了事件始末，本来想抓一下251问题网页的，当时没有电脑，不料竟然删的这么快。如果有人提供原始页面那就再好不过了，话说Web Archive的收录策略是什么

**Comment by CodeDaraW** [comment]
Web Archive 的策略我也不太了解，好在 Google Cache 还是有的，至少保留了大部分内容。  
知乎有网友保留了原始页面的 PDF，但目前还没有联系上他。
