### ISSUE TITLE
关于251事件

### ISSUE THREAD

**Issue by Moeologist** [evil-huawei/evil-huawei#13]
251事件之前。有知乎用户名为 华为北非林夕 的账号（已被封禁）在https://www.zhihu.com/answer/916689789 发表了了回答。是否可以收录此条

**Comment by Moeologist** [comment]
回答也已被删除，指控了北非无线部门

**Comment by Moeologist** [comment]
![](https://i.imgur.com/6MrrAVX.jpg)

**Comment by Moeologist** [comment]
![](https://i.imgur.com/iZ0UamZ.jpg)

**Comment by CodeDaraW** [comment]
Updated.
