### ISSUE TITLE
提供一份已保存的羁押251知乎问题网页快照

### ISSUE THREAD

**Issue by OmmyZhang** [evil-huawei/evil-huawei#21]
https://github.com/zhihu-huawei251/zhihu-huawei251/blob/master/2019.11.29%2007:30:07%20GMT%E7%BD%91%E9%A1%B5%E5%BF%AB%E7%85%A7.nojs.html

来源于谷歌缓存的网页快照，做了格式化并且去掉了所有js（否则会进入循环刷新没法正常显示）

**Comment by CodeDaraW** [comment]
已补充，并新增了相关项目，添加了 zhihu-huawei251/zhihu-huawei251 。
