### ISSUE TITLE
CEO宣称”like the US“

### ISSUE THREAD

**Issue by njzjz** [evil-huawei/evil-huawei#31]
典型的崇洋媚外！

![image](https://user-images.githubusercontent.com/9496702/69908899-02cf2580-13c0-11ea-82ab-9276d05b8953.png)

![image](https://user-images.githubusercontent.com/9496702/69908916-0f537e00-13c0-11ea-856e-81ca4236ffeb.png)

来自https://www.youtube.com/watch?v=Nl2jCWDwE8w

**Comment by CodeDaraW** [comment]
这是一个个人意识形态与喜好的问题，个人认为不算作恶。
且没有上下文的前提下容易被断章取义，故暂不添加。
