### ISSUE TITLE
Use Jekyll properly

### ISSUE THREAD

**Issue by ice1000** [evil-huawei/evil-huawei#5]
考虑到这个东东已经被 host 到了 GitHub Pages (Jekyll) 上，是不是应该考虑把文章按照 Jekyll 的标准放置？这样就可以自动生成作为目录的阴蒂刻字点 HTML 了，不需要手动维护。

另：这个项目的 admin 人员是不是已经暴露这是谁维护的了。

**Comment by CodeDaraW** [comment]
使用 GitHub Pages 是为了简单搞个项目主页，之前没有使用过 Jekyll，稍后看下如何调整文件目录。

目前没有去刻意隐藏这个项目维护人员，否则从一开始我就会选择完全匿名了。

**Comment by ice1000** [comment]
文档帮你找好了 https://jekyllcn.com/docs/pagination/
glfh

**Comment by CodeDaraW** [comment]
想了下我需要的其实不是自动生成作为目录的 index.html，而是根目录下的 README.md，于是简单写了个脚本搞定了。  

顺带加了个链接，这样 GitHub Pages 上的首页也有可以点击跳转的目录了。
